# Example docker-compose file: values in <?> need to be updated
# Postgres
db:
  image: 'postgres:9.1'
  ports:
    - "5432:5432"
  volumes:
    - messenger_db_data:/var/lib/postgresql/data
  environment: &dbEnvironment
    POSTGRES_DB: <production_db>
    POSTGRES_USER: <db_user>
    POSTGRES_PASSWORD: <db_password>

# Rails app
web:
  build: .
  environment:
    <<: *dbEnvironment
    RAILS_ENV: production
    SECRET_KEY_BASE: <secret_key>
    RM_HOST: <rm_host>
    RM_USER: <rm_user>
    RM_PASSWORD: <rm_password>
    SMTP_USERNAME: <smtp_user>
    SMTP_PASSWORD: <smtp_password>
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - certs:/certs
    - messenger_logs:/usr/src/app/log
  links:
    - db
