# Example docker-compose file: values in <?> need to be updated
# Postgres
db:
  image: 'postgres:9.1'
  ports:
    - "5432:5432"
  volumes:
    - messenger_db_data:/var/lib/postgresql/data
  environment:
    POSTGRES_DB: <production_db>
    POSTGRES_USER: <db_user>
    POSTGRES_PASSWORD: <mysecretpassword>

# Rails app
web:
  build: .
  environment:
    RAILS_ENV: production
    POSTGRES_USER: <db_user>
    POSTGRES_PASSWORD: <mysecretpassword>
    SECRET_KEY_BASE: <outputOfRakeSecretOrAnyRandomLongSecretKey>
  ports:
    - '80:80'
  links:
    - db
