development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DEV_DB_SCHEMA'] %>
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>
  host: <%= ENV['DEV_DB_HOST'] %>
  port: <%= ENV['DEV_DB_PORT'] %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['PROD_DB_SCHEMA'] %>
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
  host: <%= ENV['PROD_DB_HOST'] %>
  port: <%= ENV['PROD_DB_PORT'] %>
