development:
  secret_key_base: <%= ENV["DEV_SECRET_KEY_BASE"] %>
  cas_url: <%= ENV["DEV_CAS_URL"] %>
  roles_host: <%= ENV["ROLES_HOST"] %>
  roles_user: <%= ENV["ROLES_USER"] %>
  roles_password: <%= ENV["ROLES_PASSWORD"] %>
  dynamodb_region: ''
  dynamodb_access_key: ''
  dynamodb_secret_key: ''
  dynamodb_message_receipt_table: ''
  smtp_address: ''
  smtp_port: ''
  smtp_domain: ''
  smtp_username: ''
  smtp_password: ''

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cas_url: <%= ENV["CAS_URL"] %>
  roles_host: <%= ENV["ROLES_HOST"] %>
  roles_user: <%= ENV["ROLES_USER"] %>
  roles_password: <%= ENV["ROLES_PASSWORD"] %>
  dynamodb_region: ''
  dynamodb_access_key: ''
  dynamodb_secret_key: ''
  dynamodb_message_receipt_table: ''
  smtp_address: ''
  smtp_port: ''
  smtp_domain: ''
  smtp_username: ''
  smtp_password: ''

production:
  secret_key_base: <%= ENV["PROD_SECRET_KEY_BASE"] %>
  cas_url: <%= ENV["PROD_CAS_URL"] %>
  roles_host: <%= ENV["ROLES_HOST"] %>
  roles_user: <%= ENV["ROLES_USER"] %>
  roles_password: <%= ENV["ROLES_PASSWORD"] %>
  dynamodb_region: <%= ENV["PROD_DYNAMODB_REGION"] %>
  dynamodb_access_key: <%= ENV["PROD_DYNAMODB_AWS_ACCESS_KEY"] %>
  dynamodb_secret_key: <%= ENV["PROD_DYNAMODB_AWS_SECRET_KEY"] %>
  dynamodb_message_receipt_table: <%= ENV["PROD_DYNAMODB_MESSAGE_RECEIPT_TABLE"] %>
  smtp_address: <%= ENV["PROD_SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["PROD_SMTP_PORT"] %>
  smtp_domain: <%= ENV["PROD_SMTP_DOMAIN"] %>
  smtp_username: <%= ENV["PROD_SMTP_USERNAME"] %>
  smtp_password: <%= ENV["PROD_SMTP_PASSWORD"] %>
