development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cas_url: <%= ENV["CAS_URL"] %>
  roles_host: <%= ENV["ROLES_HOST"] %>
  roles_user: <%= ENV["ROLES_USER"] %>
  roles_password: <%= ENV["ROLES_PASSWORD"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cas_url: <%= ENV["CAS_URL"] %>
  roles_host: <%= ENV["ROLES_HOST"] %>
  roles_user: <%= ENV["ROLES_USER"] %>
  roles_password: <%= ENV["ROLES_PASSWORD"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cas_url: <%= ENV["CAS_URL"] %>
  roles_host: <%= ENV["ROLES_HOST"] %>
  roles_user: <%= ENV["ROLES_USER"] %>
  roles_password: <%= ENV["ROLES_PASSWORD"] %>
